INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'chuck@gmail.com', N'chuck', N'1234', 0)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir@gmail.com', N'Meiz', N'1234', 1)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir+1@gmail.com', N'Meir Shtarkman', N'1234', 0)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir+5@gmail.com', N'Meir Shtar', N'1234', 1)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir+8@gmail.com', N'Meir Shtar', N'1234', 1)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir6@gmail.com', N'meiz', N'1234', 2)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir7@gmail.com', N'Meir Shtar', N'1234', 1)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'meir8@gmail.com', N'Meir Shtar', N'1234', 2)
INSERT INTO [dbo].[Users] ([Email], [Name], [Password], [Figure]) VALUES (N'ron@gmail.com', N'ron', N'1234', 0)
